### ISSUE TITLE
Unable to use with latest versions of library

### ISSUE THREAD

**Issue by bergstar** [DesignByCode/tailwindcss-text-stroke#1]
Maybe its just my setup, however I get this error when following documentation
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@designbycode/conic tailwindcss-text-stroke' imported from /*/tailwind.config.js`

When changing to 
`      import("@designbycode/tailwindcss-text-stroke"),
`

There is an error in package.json
```
  "exports": {
    ".": {
      "import": "./dist/index.js",
```

Where it refers to index.js however only index.cjs is present

**Comment by claudemyburgh** [comment]
Sorry the package name was wrong in docs. should be @designbycode/tailwindcss-text-stroke
